ALTER TABLE products ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP;
ALTER TABLE products ADD COLUMN IF NOT EXISTS verified_by INT;
